# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: chaos-admin
#   namespace: chaos-testing
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: chaos-admin-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: cluster-admin
# subjects:
#   - kind: ServiceAccount
#     name: chaos-admin
#     namespace: chaos-testing

# chaos-testing-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-mesh-operator
  namespace: chaos-testing
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jen-chaos-access
  namespace: chaos-testing
subjects:
- kind: User
  name: jen
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chaos-mesh-operator
  apiGroup: rbac.authorization.k8s.io
