apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-nginx-kill
  namespace: chaos-testing
spec:
  schedule: "@every 1m"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - chaos-testing
      labelSelectors:
        app: nginx
    duration: "30s"

