apiVersion: v1
kind: Pod
metadata:
  name: dns-debug
  namespace: chaos-testing
  labels:
    app: dns-debug
spec:
  containers:
    - name: dns
      image: busybox:1.28
      command: ['sh', '-c', 'sleep 3600']
      stdin: true
      tty: true
  restartPolicy: Always
